USE sales;

SELECT * FROM transactions;
SELECT * FROM customers;
SELECT * FROM date;
SELECT * FROM markets;
SELECT * FROM products;

-- Get the total no. of transactions.
SELECT COUNT(*) FROM transactions;

-- Get the total no. of transactions.
SELECT COUNT(*) FROM customers;

-- Get the total no. of products.
SELECT COUNT(*) FROM products;

-- Get the total no. of markets.
SELECT COUNT(*) FROM markets;

-- In which different currencies transactions have been made?
SELECT DISTINCT currency FROM transactions;

-- Find the total revenue.
SELECT SUM(sales_amount) FROM transactions;

-- Find total revenue generated in each year.
SELECT year, SUM(sales_amount) as revenue
FROM transactions JOIN date
ON transactions.order_date = date.date
GROUP BY year;

-- Find total sales quantity in each year.
SELECT year, SUM(sales_qty)
FROM transactions JOIN date
ON transactions.order_date = date.date
GROUP BY year;

-- Find total revenue generated by each market and arrange them in decreasing order.
SELECT markets_code, SUM(sales_amount) as revenue
FROM transactions
JOIN markets
ON transactions.market_code=markets.markets_code
GROUP BY markets_code
ORDER BY revenue DESC;

-- Find total revenue generated by each zone and arrange them in decreasing order.
SELECT zone, SUM(sales_amount) as revenue
FROM transactions
JOIN markets
ON transactions.market_code=markets.markets_code
GROUP BY zone
ORDER BY revenue DESC;

-- Find top 5 customers in terms of revenue.
SELECT custmer_name, SUM(sales_amount) as revenue
FROM transactions
JOIN customers
ON transactions.customer_code=customers.customer_code
GROUP BY custmer_name
ORDER BY revenue DESC
LIMIT 5;

-- Find top 5 products in terms of revenue.
SELECT transactions.product_code, SUM(sales_amount) as revenue
FROM transactions
JOIN products
ON transactions.product_code=products.product_code
GROUP BY product_code
ORDER BY revenue DESC
LIMIT 5;

-- Find the total profit margin.
SELECT SUM(profit_margin) FROM transactions;

-- Find total profit margin generated by each market.
SELECT markets_name,SUM(profit_margin) as total_profit_margin
FROM transactions
JOIN markets
ON transactions.market_code=markets.markets_code
GROUP BY markets_name
ORDER BY total_profit_margin DESC;

-- Find total profit margin generated by each zone.
SELECT zone,SUM(profit_margin) as total_profit_margin
FROM transactions
JOIN markets
ON transactions.market_code=markets.markets_code
GROUP BY zone
ORDER BY total_profit_margin DESC;



